DELIMITER $$

CREATE PROCEDURE 'sp_select_hub'
{
	DECLARE heure_min INTEGER DEFAULT 0;
	DECLARE minute_min INTEGER DEFAULT 0;
	DECLARE heure_max INTEGER DEFAULT 23;
	DECLARE minute_max INTEGRER DEFAULT 45;
}
BEGIN

SELECT * FROM hub

END$$

DELIMITER;
